#ifndef EJERCICIO_09_H_INCLUDED
#define EJERCICIO_09_H_INCLUDED

enum MES {ENERO=1, FEBRERO=2, MARZO=3, ABRIL=4, MAYO=5, JUNIO=6, JULIO=7, AGOSTO=8, SEPTIEMBRE=9, OCTUBRE=10, NOVIEMBRE=11, DICIEMBRE=12};

int obtenerDiasDelMes(int mes, int anio);

#endif // EJERCICIO_09_H_INCLUDED
